THEYALOW layout
olga-arkhipenko/olga-arkhipenko.github.io pull request #1
Opened 2018-02-12 14:07 UTC by olga-arkhipenko

2018-02-13 12:09 UTC, ahryhoryeu requested changes
There a few additional UI issues:
1. Letter-spacing is missing in many places.
2. Line height seems to be missing in the features list.
3. Header menu shadow doesn't seem to be of the same color as the menu background. It should use the same color and have transcparency.

2018-02-13 12:09 UTC, ahryhoryeu commented on styles/blocks/header-banner.css
> +  color: #fff;
It's great you don't use `color: white`, but still you need to be consistent and always describe colors with 6 hex digits in lower case, or use `rgba` format, or `hsla`.

2018-02-13 12:09 UTC, ahryhoryeu commented on styles/blocks/header-banner.css
> +.header-banner__title--yellow {
In fact, `--yellow` modifier is kinda poor in terms of naming. Since the visual design is a subject to changes, it's better to stick to semantics, for example, have `--primary` and `--secondary` modifiers.

2018-02-13 12:09 UTC, ahryhoryeu commented on styles/blocks/header.css
> +  margin: auto;
I doubt this is needed since you already have a `container` inside.

2018-02-13 12:09 UTC, ahryhoryeu commented on index.html
> +        <ul class="main-menu">
To be more semantic, you could've used `<nav>` here.

2018-02-13 12:09 UTC, ahryhoryeu commented on index.html
>        <div class="container">
This `<div>` doesn't seem to be closed.

2018-02-13 12:09 UTC, ahryhoryeu commented on styles/blocks/section-features.css
> +.section-features__item:nth-child(odd) {
Unfortunately, this solution is not generic enough. Imagine there's another item added a there are 4 items in that row - there won't be any border on the right. Please opt for a more generic solution.

2018-02-13 12:09 UTC, ahryhoryeu commented on styles/blocks/section-features.css
> +  flex-basis: 120px;
Basically you're giving a static width to this element, which is not a good practice. In this case your items won't scale for smaller devices. I noticed such use in other places, please opt for another ways.

2018-02-13 12:09 UTC, ahryhoryeu commented on styles/blocks/section-about-us.css
> +  max-height: 232px;
`max-height` restrcition leads to the following issue: https://www.screencast.com/t/p72zoBKXSVW
Adding more content should break the UI. This pricinple is applicable everywhere across the page.

2018-02-13 12:09 UTC, ahryhoryeu commented on styles/blocks/section-features.css
> +  flex-basis: 120px;
It may be the case that using flex everywhere is not the best idea after all: read more here https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox.

2018-02-13 12:09 UTC, ahryhoryeu commented on styles/blocks/section-benefits.css
> +  list-style-image: url(../../images/section-benefits/dot.png);
Not bad, but it can be done simpler without any images. Use `list-style-type: disc` and have different font-sizes for the list elements and their content.

2018-02-13 12:09 UTC, ahryhoryeu commented on index.html
> +      <img src="./images/primary-logo.png" class="footer__logo-img" alt="THEYALOW logo">
This doesn't seem to be a complete block re-use. What do you think of having an additional modifier class `primary-logo--small` or smth better and declaring in CSS that with this modifier `logo-img` and `logo-name` have different styling?

2018-02-14 08:16 UTC, olga-arkhipenko commented on styles/blocks/header-banner.css
> +  color: #fff;
fixed.

2018-02-14 08:17 UTC, olga-arkhipenko commented on styles/blocks/header-banner.css
> +.header-banner__title--yellow {
fixed.

2018-02-14 08:17 UTC, olga-arkhipenko commented on styles/blocks/header.css
> +  margin: auto;
fixed.

2018-02-14 08:22 UTC, olga-arkhipenko commented on index.html
>        <div class="container">
fixed.

2018-02-18 12:30 UTC, olga-arkhipenko commented on index.html
> +        <ul class="main-menu">
fixed.

2018-02-18 12:31 UTC, olga-arkhipenko commented on styles/blocks/section-features.css
> +.section-features__item:nth-child(odd) {
fixed.

2018-02-19 13:00 UTC, olga-arkhipenko commented on styles/blocks/section-features.css
> +  flex-basis: 120px;
fixed.

2018-02-19 13:00 UTC, olga-arkhipenko commented on styles/blocks/section-features.css
> +.section-features__item:nth-child(odd) {
fixed.

2018-02-19 13:00 UTC, olga-arkhipenko commented on index.html
> +        <ul class="main-menu">
fixed.

2018-02-19 14:33 UTC, olga-arkhipenko commented on index.html
> +      <img src="./images/primary-logo.png" class="footer__logo-img" alt="THEYALOW logo">
fixed.

2018-02-20 07:06 UTC, olga-arkhipenko commented on styles/blocks/section-benefits.css
> +  list-style-image: url(../../images/section-benefits/dot.png);
fixed.

2018-02-20 07:06 UTC, olga-arkhipenko commented on styles/blocks/section-about-us.css
> +  max-height: 232px;
fixed.

2018-02-20 10:31 UTC, ahryhoryeu requested changes

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/container.css
> +    max-width: 1020px;
Later, when you're going to be doing RWD, it would make sense to say that when the screen is wider than `1020px`, container should have just `width: 1020px`. Otherwise, `max-width: 100%`, for example.

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/container.css
> +    margin: auto;
To avoid any possible implications, it may make sense to explicitly say `margin: 0 auto;`.

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/header-banner.css
> +    width: 54.8%;
Are you sure it makes sense to be so pixel-perfect to use fractions of percent?

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/header-banner.css
> +    padding: 74px 0 0 30px;
Semantically, these seem more like margins, but I assume changing it to paddings may mean redesigning `header-banner` block, so probably let it be.

2018-02-20 10:31 UTC, ahryhoryeu commented on index.html
> +                    <a href="#" class="link">
This link lacks `display: block` in order to occupy all of its parent's space. It's inline by default, so here's what it looks like right now: https://www.screencast.com/t/7fqg9tun2JV.

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/primary-logo.css
> +.primary-logo__name--small {
It would seem to me more natural if the modifier was only applied to the whole block, and then using nesting selector the element could be modified:
```css
.primary-logo--small .primary-logo__name {
    padding: 0 0 8px;
    ...
}
```

If you can provide arguments that this is against BEM, then fine.

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/section-about-us.css
> +    float: left;
Lack of `clear-fix` for containers with floating elements leads to its collapsing. https://www.screencast.com/t/d53TvveTVt
https://wiki.itechart-group.com/download/attachments/17793055/overflow-float.png?version=1&modificationDate=1435327005377&api=v2

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/section-about-us.css
> +.section-about-us__video {
Unfortunately, this block still doesn't have the desired behavior when there's more text than the design provides. 
![2018-02-20_1212](https://user-images.githubusercontent.com/23052050/36415616-9954d532-1637-11e8-9dcf-dd702b57d359.png)
Here's what I though it would look like: 
![2018-02-20_1220](https://user-images.githubusercontent.com/23052050/36415876-77a2bc96-1638-11e8-80ca-29102250f469.png)

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/section-about-us.css
> +    width: 32.3529412%;
WHY?

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/section-about-us.css
> +    left: 86%;
Would using `right` property be more suitable here?

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/section-about-us.css
> +.section-about-us__social-plus {
On the UI, this icon does look smaller than it has to be.

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/section-benefits.css
> +.section-benefits__items-list {
It seems better to separate the list in a s block. This class is still valueable, but it only should position an element inside `section-benefits` block. The list could be a separate block, and you could mix classes on the `ul` element, so it would be smth like `<ul class="items-list section-benefits__items-list">` and then every class will have its own responsibilities.

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/section-features.css
> +    width: 33%;
Opt for using `width: 33.33%` in such cases. Loosing 1% of width can be noticable here.

2018-02-20 10:31 UTC, ahryhoryeu commented on styles/blocks/section-features.css
> +    display: table;
Did you consider using CSS Grids here? What was the reason behind using `display: table`?

2018-02-20 11:13 UTC, olga-arkhipenko commented on styles/blocks/section-features.css
> +    display: table;
I used it for vertical alignment inside each seaction-feature__item using `display: table-cell`. So items parent is `display: table`

2018-02-20 12:50 UTC, olga-arkhipenko commented on styles/blocks/container.css
> +    margin: auto;
fixed.

2018-02-20 12:55 UTC, olga-arkhipenko commented on styles/blocks/header-banner.css
> +    width: 54.8%;
no more pixel perfect, fixed.

2018-02-20 13:13 UTC, olga-arkhipenko commented on styles/blocks/header-banner.css
> +    padding: 74px 0 0 30px;
Added a wrapper for this

2018-02-20 13:22 UTC, olga-arkhipenko commented on index.html
> +                    <a href="#" class="link">
fixed.

2018-02-20 13:26 UTC, olga-arkhipenko commented on styles/blocks/primary-logo.css
> +.primary-logo__name--small {
ok, did it nested.

2018-02-20 13:28 UTC, olga-arkhipenko commented on styles/blocks/section-about-us.css
> +    width: 32.3529412%;
'cos life is hard.

2018-02-20 13:29 UTC, olga-arkhipenko commented on styles/blocks/section-about-us.css
> +    left: 86%;
u r right!

2018-02-20 13:29 UTC, olga-arkhipenko commented on styles/blocks/section-about-us.css
> +    width: 32.3529412%;
fixed.

2018-02-20 13:29 UTC, olga-arkhipenko commented on styles/blocks/section-about-us.css
> +    left: 86%;
fixed.

2018-02-20 13:36 UTC, olga-arkhipenko commented on styles/blocks/section-about-us.css
> +.section-about-us__social-plus {
fixed.

2018-02-20 13:37 UTC, olga-arkhipenko commented on styles/blocks/section-features.css
> +    width: 33%;
ok

2018-02-20 14:14 UTC, olga-arkhipenko commented on styles/blocks/section-benefits.css
> +.section-benefits__items-list {
made them separate.

2018-02-21 07:47 UTC, ahryhoryeu approved these changes

2018-02-21 07:47 UTC, ahryhoryeu commented on .gitignore
> +*.csscomb.json
CSScomb config should *not* be ignored. It's a way to keep the codebase consistent, so all linters' configs should be commited into the repository.

2018-02-21 07:47 UTC, ahryhoryeu commented on index.html
> +                        <li class="list__item section-benefits__list-item">
Forgotten class `section-benefits-list-item`.

2018-02-21 07:47 UTC, ahryhoryeu commented on styles/blocks/list.css
> +.list__item__content {
Elements of elements are disallowed. Did you mean `list__item-content`?

2018-02-21 07:47 UTC, ahryhoryeu commented on index.html
> +                    <p class="section-about-us__social-count">22</p>
Based on the name of the classes (`section-about-us__social`, `section-about-us__social-count`, `section-about-us__social-twitter`, `section-about-us__social-plus`) and on their number, I guess it also makes sense to create a block for this `social` thing.

2018-02-21 07:47 UTC, ahryhoryeu commented on index.html
> +                <div class="section-about-us__video">
The same here as below for social. Video with description may look like a separate block to me.

2018-02-21 09:26 UTC, olga-arkhipenko commented on .gitignore
> +*.csscomb.json
fixed.

2018-02-21 09:26 UTC, olga-arkhipenko commented on index.html
> +                        <li class="list__item section-benefits__list-item">
fixed.

2018-02-21 09:26 UTC, olga-arkhipenko commented on styles/blocks/list.css
> +.list__item__content {
yes, sure

2018-02-21 10:45 UTC, merged